package com.mandrecode.tempo.core.ui.theme

import androidx.compose.ui.graphics.Color

// region Tempo Brand
val TempoBrandPrimary = Color(0xFF006A60)
val TempoBrandBackground = Color(0xFFCCE8E3)
// endregion

// region Tempo Light Scheme
val TempoLightPrimary = TempoBrandPrimary
val TempoLightOnPrimary = Color(0xFFFFFFFF)
val TempoLightPrimaryContainer = Color(0xFF9EF2E4)
val TempoLightOnPrimaryContainer = Color(0xFF005048)
val TempoLightInversePrimary = Color(0xFF82D5C8)
val TempoLightSecondary = Color(0xFF4A635F)
val TempoLightOnSecondary = Color(0xFFFFFFFF)
val TempoLightSecondaryContainer = Color(0xFFCCE8E2)
val TempoLightOnSecondaryContainer = Color(0xFF334B47)
val TempoLightTertiary = Color(0xFF466179)
val TempoLightOnTertiary = Color(0xFFFFFFFF)
val TempoLightTertiaryContainer = Color(0xFFCCE5FF)
val TempoLightOnTertiaryContainer = Color(0xFF2D4961)
val TempoLightBackground = Color(0xFFF4FBF8)
val TempoLightOnBackground = Color(0xFF161D1C)
val TempoLightSurface = Color(0xFFF4FBF8)
val TempoLightOnSurface = Color(0xFF161D1C)
val TempoLightSurfaceVariant = Color(0xFFDAE5E2)
val TempoLightOnSurfaceVariant = Color(0xFF3F4947)
val TempoLightSurfaceTint = TempoBrandPrimary
val TempoLightInverseSurface = Color(0xFF2B3230)
val TempoLightInverseOnSurface = Color(0xFFECF2EF)
val TempoLightError = Color(0xFFBA1A1A)
val TempoLightOnError = Color(0xFFFFFFFF)
val TempoLightErrorContainer = Color(0xFFFFDAD6)
val TempoLightOnErrorContainer = Color(0xFF93000A)
val TempoLightOutline = Color(0xFF6F7977)
val TempoLightOutlineVariant = Color(0xFFBEC9C6)
val TempoLightScrim = Color(0xFF000000)
val TempoLightSurfaceDim = Color(0xFFD5DBD9)
val TempoLightSurfaceBright = Color(0xFFF4FBF8)
val TempoLightSurfaceContainerLowest = Color(0xFFFFFFFF)
val TempoLightSurfaceContainerLow = Color(0xFFEFF5F2)
val TempoLightSurfaceContainer = Color(0xFFE9EFED)
val TempoLightSurfaceContainerHigh = Color(0xFFE3EAE7)
val TempoLightSurfaceContainerHighest = Color(0xFFDDE4E1)
// endregion

// region Tempo Dark Scheme
val TempoDarkPrimary = Color(0xFF82D5C8)
val TempoDarkOnPrimary = Color(0xFF003732)
val TempoDarkPrimaryContainer = Color(0xFF005048)
val TempoDarkOnPrimaryContainer = Color(0xFF9EF2E4)
val TempoDarkInversePrimary = TempoBrandPrimary
val TempoDarkSecondary = Color(0xFFB1CCC6)
val TempoDarkOnSecondary = Color(0xFF1C3531)
val TempoDarkSecondaryContainer = Color(0xFF334B47)
val TempoDarkOnSecondaryContainer = Color(0xFFCCE8E2)
val TempoDarkTertiary = Color(0xFFADCAE6)
val TempoDarkOnTertiary = Color(0xFF153349)
val TempoDarkTertiaryContainer = Color(0xFF2D4961)
val TempoDarkOnTertiaryContainer = Color(0xFFCCE5FF)
val TempoDarkBackground = Color(0xFF0E1513)
val TempoDarkOnBackground = Color(0xFFDDE4E1)
val TempoDarkSurface = Color(0xFF0E1513)
val TempoDarkOnSurface = Color(0xFFDDE4E1)
val TempoDarkSurfaceVariant = Color(0xFF3F4947)
val TempoDarkOnSurfaceVariant = Color(0xFFBEC9C6)
val TempoDarkSurfaceTint = Color(0xFF82D5C8)
val TempoDarkInverseSurface = Color(0xFFDDE4E1)
val TempoDarkInverseOnSurface = Color(0xFF2B3230)
val TempoDarkError = Color(0xFFFFB4AB)
val TempoDarkOnError = Color(0xFF690005)
val TempoDarkErrorContainer = Color(0xFF93000A)
val TempoDarkOnErrorContainer = Color(0xFFFFDAD6)
val TempoDarkOutline = Color(0xFF899390)
val TempoDarkOutlineVariant = Color(0xFF3F4947)
val TempoDarkScrim = Color(0xFF000000)
val TempoDarkSurfaceDim = Color(0xFF0E1513)
val TempoDarkSurfaceBright = Color(0xFF343A39)
val TempoDarkSurfaceContainerLowest = Color(0xFF090F0E)
val TempoDarkSurfaceContainerLow = Color(0xFF161D1C)
val TempoDarkSurfaceContainer = Color(0xFF1A2120)
val TempoDarkSurfaceContainerHigh = Color(0xFF252B2A)
val TempoDarkSurfaceContainerHighest = Color(0xFF303635)
// endregion

// region Pastel Picker Colors (M3 Tonal Palette - Tone 40 Light / Tone 80 Dark)
val PastelBlueLight = Color(0xFF0061A4)
val PastelBlueDark = Color(0xFF9FCAFF)
val PastelGreenLight = Color(0xFF4C662B)
val PastelGreenDark = Color(0xFFB1D18A)
val PastelYellowLight = Color(0xFF695F00)
val PastelYellowDark = Color(0xFFD6C64D)
val PastelOrangeLight = Color(0xFF944B00)
val PastelOrangeDark = Color(0xFFFFB77C)
val PastelRedLight = Color(0xFFBC1127)
val PastelRedDark = Color(0xFFFFB3AD)
val PastelPinkLight = Color(0xFF984061)
val PastelPinkDark = Color(0xFFFFB1C8)
val PastelPurpleLight = Color(0xFF6B4EA2)
val PastelPurpleDark = Color(0xFFD3BBFF)
val PastelCyanLight = Color(0xFF006874)
val PastelCyanDark = Color(0xFF9EEFFD)
// endregion
