#!/usr/bin/env python3
"""Generates the demo-data SQL for Google Play Store screenshots (GitHub
issue #169), with every date computed relative to "today" so the seeded
"Today" tasks, due dates, and habit streaks stay correct no matter when the
pipeline is run. Not part of the CI/app build.

Usage: generate-seed-sql.py [--today YYYY-MM-DD] > seed.sql
"""
import argparse
import datetime


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--today",
        type=datetime.date.fromisoformat,
        default=datetime.date.today(),
        help="Reference date to treat as 'today' (default: actual today).",
    )
    return parser.parse_args()


def d(today, offset_days):
    """ISO date offset_days from today, e.g. d(today, -1) == yesterday."""
    return (today + datetime.timedelta(days=offset_days)).isoformat()


def dt(today, offset_days, time):
    """ISO datetime (no seconds) offset_days from today at the given time."""
    return f"{d(today, offset_days)}T{time}"


def history(today, start_offset, end_offset):
    """Comma-separated ISO dates from start_offset to end_offset (inclusive)."""
    return ",".join(d(today, o) for o in range(start_offset, end_offset + 1))


def history_with_gaps(today, offsets):
    return ",".join(d(today, o) for o in offsets)


def sql_str(value):
    return "NULL" if value is None else "'" + value.replace("'", "''") + "'"


def main():
    args = parse_args()
    today = args.today

    print(
        "-- Demo data for Google Play Store screenshots (GitHub issue #169).\n"
        "-- Generated by scripts/generate-seed-sql.py — do not edit directly.\n"
        "-- Run only against a freshly created app DB (Inbox category already\n"
        "-- seeded by TempoDatabase.inboxCallback).\n",
    )

    print(
        "INSERT INTO categories (id, name, color, icon, isDefault, sortOrder) VALUES\n"
        "  (1, 'Work', 'color_m3_blue', 'work', 0, 0),\n"
        "  (2, 'Shopping', 'color_m3_orange', 'shopping_cart', 0, 1),\n"
        "  (3, 'Health', 'color_m3_red', 'health', 0, 2),\n"
        "  (4, 'Personal', 'color_m3_green', 'home', 0, 3);\n",
    )

    tasks = [
        (1, "Finish Q3 budget report", "Compile numbers from finance and send to leadership by Friday.",
         0, 1, "HIGH", dt(today, 0, "09:00"), None, None, None, None, 0, None),
        (2, "Reply to client emails", "", 0, 1, "MEDIUM", None, None, None, None, None, 1, None),
        (3, "Review pull requests", "Check the two open PRs from the mobile team.",
         1, 1, None, None, None, None, None, None, 2, dt(today, -1, "17:30")),
        (4, "Buy groceries", "Milk, eggs, spinach, coffee beans.", 0, 2, "LOW", None, None, None, None, None, 3, None),
        (5, "Order birthday gift for Mom", "", 0, 2, "MEDIUM", dt(today, 2, "12:00"), None, None, None, None, 4, None),
        (6, "Pick up dry cleaning", "", 1, 2, None, None, None, None, None, None, 5, dt(today, -2, "18:00")),
        (7, "Book dentist appointment", "Six-month checkup, call before 5pm.",
         0, 3, "MEDIUM", None, None, None, None, None, 6, None),
        (8, "Refill prescription", "", 1, 3, None, None, None, None, None, None, 7, dt(today, -3, "10:00")),
        (9, "Plan weekend hike", "Check trail conditions and pack the day before.",
         0, 4, None, None, None, None, None, None, 8, None),
        (10, "Call Mom", "", 0, 4, "HIGH", dt(today, 0, "19:00"), None, None, None, None, 9, None),
        (11, "Read 20 pages", "", 0, 4, None, None, "DAILY", None, None, None, 10, None),
        (12, "Water the plants", "", 0, -1, None, None, "WEEKLY", "1,4", None, None, 11, None),
    ]
    print("INSERT INTO tasks (id, title, description, isCompleted, categoryId, priority, reminderDate, "
          "periodicity, periodicityInterval, repeatDays, monthDayOption, parentTaskId, sortOrder, "
          "completedAt, nextInstanceId) VALUES")
    rows = []
    for (task_id, title, desc, completed, cat_id, priority, reminder, periodicity,
         repeat_days, month_day, _unused, sort_order, completed_at) in tasks:
        rows.append(
            f"  ({task_id}, {sql_str(title)}, {sql_str(desc)}, {completed}, {cat_id}, "
            f"{sql_str(priority)}, {sql_str(reminder)}, {sql_str(periodicity)}, 1, "
            f"{sql_str(repeat_days)}, {sql_str(month_day)}, NULL, {sort_order}, "
            f"{sql_str(completed_at)}, NULL)",
        )
    print(",\n".join(rows) + ";\n")

    habits = [
        (1, "Drink Water", "water", "color_m3_cyan", 1, "BUILD", -60, history(today, -5, 0)),
        (2, "No Smoking", "smoke_free", "color_m3_red", 1, "QUIT", -60, history(today, -20, 0)),
        (3, "Read Before Bed", "book", "color_m3_orange", 1, "BUILD", -60,
         history_with_gaps(today, [-7, -6, -4, -3, -2, 0])),
        (4, "Limit Social Media", "psychology", "color_m3_purple", 0, "QUIT", -30, history(today, -8, -1)),
        (5, "Meditate", "spa", "color_m3_purple", 1, "BUILD", -60, history(today, -4, 0)),
        (6, "Morning Stretch", "fitness", "color_m3_blue", 1, "BUILD", -60, history(today, -4, 0)),
        (7, "Journal", "edit_note", "color_tempo_green", 1, "BUILD", -60, history(today, -4, 0)),
    ]
    print("INSERT INTO habits (id, title, description, icon, colorKey, reminderDate, isCompleted, "
          "habitType, createdDate, completionHistory, repeatDays) VALUES")
    rows = []
    for (habit_id, title, icon, color_key, completed, habit_type, created_offset, completion) in habits:
        rows.append(
            f"  ({habit_id}, {sql_str(title)}, '', {sql_str(icon)}, {sql_str(color_key)}, NULL, "
            f"{completed}, '{habit_type}', {sql_str(dt(today, created_offset, '00:00'))}, "
            f"{sql_str(completion)}, NULL)",
        )
    print(",\n".join(rows) + ";\n")

    print(
        "INSERT INTO habit_chains (id, title, description, colorKey, icon, periodicReminder, "
        "createdDate, completionHistory, repeatDays) VALUES\n"
        f"  (1, 'Morning Routine', 'Meditate, stretch, and journal before starting the day.', "
        f"'color_m3_purple', 'spa', {sql_str(dt(today, 1, '07:00'))}, "
        f"{sql_str(dt(today, -60, '00:00'))}, {sql_str(history(today, -4, 0))}, NULL);\n",
    )

    print(
        "INSERT INTO habit_chain_members (chainId, habitId, sortOrder) VALUES\n"
        "  (1, 5, 0),\n"
        "  (1, 6, 1),\n"
        "  (1, 7, 2);",
    )


if __name__ == "__main__":
    main()
